### ISSUE TITLE
Pass --http-always-get to link-checker?

### ISSUE THREAD

**Issue by rakuco** [marcoscaceres/respec-validator#1]
For some reason, Google-hosted websites such as https://www.chromestatus.com and https://bugs.chromium.org return HTTP 405 when a HEAD request is sent to them. This causes spec validation to fail in e.g. https://github.com/w3c/wake-lock (e.g. https://travis-ci.org/w3c/wake-lock/builds/528742323):

```
could not fetch external page: Error: Method Not Allowed (Code: 405) from output.html to https://chromestatus.com/features/4636879949398016
```

I wonder if making link-checker default to sending GET requests is an acceptable workaround.

**Comment by marcoscaceres** [comment]
Our plan is to move off Chrome status and use caniuse.com instead. We have an API entpoint for that... just someone needs to request this API gets added to caniuse.com.

**Comment by marcoscaceres** [comment]
Oh whoops, wrong repo. Though we were still in the wake lock repo :P

**Comment by marcoscaceres** [comment]
> I wonder if making link-checker default to sending GET requests is an acceptable workaround.

I'm relying on [npm link-checker](https://www.npmjs.com/package/link-checker) to do the link checking... I wonder if we can use:  `--http-status-ignore 405`

**Comment by marcoscaceres** [comment]
@rakuco sorry, my brain is not working today... `--http-always-get` would probably work.
