### ISSUE TITLE
Provide as a github action

### ISSUE THREAD

**Issue by dontcallmedom** [marcoscaceres/respec-validator#7]
Could this be provided as a [github action](https://help.github.com/en/actions/creating-actions/creating-a-javascript-action), with the various CLI parameters turned into action parameters? This would help with deploying it on spec repos.

**Comment by sidvishnoi** [comment]
There is a GitHub action to validate (using this validator) and deploy on TR (using echidna) though, if that's the end goal. See https://github.com/w3c/respec-w3c-auto-publish

**Comment by dontcallmedom** [comment]
ah, thanks, I didn't know; the auto-publish part is useful for WDs, but probably not for CRs - is that configurable?

**Comment by sidvishnoi** [comment]
> is that configurable?

Not yet, but can do. Might be better to create this as separate action, as the other one aims to be a publish helper.

**Comment by sidvishnoi** [comment]
It's pretty straight forward to use it directly in a workflow though, so not quite sure how much value it will provide:
``` yaml
- run: npx respec-validator --no-links index.html
```

**Comment by dontcallmedom** [comment]
good point - I'll go with that then - thanks!

**Comment by sidvishnoi** [comment]
@dontcallmedom It might be helpful if you add the following in your workflow, as it'll speed things up.
``` yaml
env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
```

**Comment by dontcallmedom** [comment]
could this be documented on the README then :)?
